export const GET_AUTH_DATA = 'GET_AUTH_DATA';
export type T_GET_AUTH_DATA = typeof GET_AUTH_DATA;

export const GET_AUTH_DATA_FAILED = 'GET_AUTH_DATA_FAILED';
export type T_GET_AUTH_DATA_FAILED = typeof GET_AUTH_DATA_FAILED;

export const GET_AUTH_DATA_SUCCESS = 'GET_AUTH_DATA_SUCCESS';
export type T_GET_AUTH_DATA_SUCCESS = typeof GET_AUTH_DATA_SUCCESS;