export const GOTO_NEW_TODO_PERSONAL = 'GOTO_NEW_TODO_PERSONAL';
export type T_GOTO_NEW_TODO_PERSONAL = typeof GOTO_NEW_TODO_PERSONAL;

export const SET_TODO_DETAIL_ITEM = 'SET_TODO_DETAIL_ITEM';
export type T_SET_TODO_DETAIL_ITEM = typeof SET_TODO_DETAIL_ITEM;

export const CREATE_TODO_LOCAL = 'CREATE_TODO_LOCAL';
export type T_CREATE_TODO_LOCAL = typeof CREATE_TODO_LOCAL;

export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export type T_CREATE_TODO_SUCCESS = typeof CREATE_TODO_SUCCESS;

export const CREATE_TODO_FAILED = 'CREATE_TODO_FAILED';
export type T_CREATE_TODO_FAILED = typeof CREATE_TODO_FAILED;

export const UPDATE_TODO_LOCAL = 'UPDATE_TODO_LOCAL';
export type T_UPDATE_TODO_LOCAL = typeof UPDATE_TODO_LOCAL;

export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export type T_UPDATE_TODO_SUCCESS = typeof UPDATE_TODO_SUCCESS;

export const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED';
export type T_UPDATE_TODO_FAILED = typeof UPDATE_TODO_FAILED;

export const GET_ALL_TODOS_LOCAL = 'GET_ALL_TODOS_LOCAL';
export type T_GET_ALL_TODOS = typeof GET_ALL_TODOS_LOCAL;

export const GET_ALL_TODOS_LOCAL_SUCCESS = 'GET_ALL_TODOS_LOCAL_SUCCESS';
export type T_GET_ALL_TODOS_LOCAL_SUCCESS = typeof GET_ALL_TODOS_LOCAL_SUCCESS;

export const GET_ALL_TODOS_LOCAL_FAILED = 'GET_ALL_TODOS_LOCAL_FAILED';
export type T_GET_ALL_TODOS_LOCAL_FAILED = typeof GET_ALL_TODOS_LOCAL_FAILED;

export const GET_LOCAL_TODO_ATTACHMENTS = 'GET_LOCAL_TODO_ATTACHMENTS';
export type T_GET_LOCAL_TODO_ATTACHMENTS = typeof GET_LOCAL_TODO_ATTACHMENTS;

export const GET_LOCAL_TODO_ATTACHMENTS_FAILED = 'GET_LOCAL_TODO_ATTACHMENTS_FAILED';
export type T_GET_LOCAL_TODO_ATTACHMENTS_FAILED = typeof GET_LOCAL_TODO_ATTACHMENTS_FAILED;

export const GET_LOCAL_TODO_ATTACHMENTS_SUCCESS = 'GET_LOCAL_TODO_ATTACHMENTS_SUCCESS';
export type T_GET_LOCAL_TODO_ATTACHMENTS_SUCCESS = typeof GET_LOCAL_TODO_ATTACHMENTS_SUCCESS;

export const MARK_LOCAL_TODO_AS_DONE_OR_EMPHASIZED_SUCCESS = 'MARK_LOCAL_TODO_AS_DONE_OR_EMPHASIZED_SUCCESS';
export type T_MARK_LOCAL_TODO_AS_DONE_OR_EMPHASIZED_SUCCESS = typeof MARK_LOCAL_TODO_AS_DONE_OR_EMPHASIZED_SUCCESS;

export const MARK_LOCAL_TODO_AS_DONE_OR_EMPHASIZED_FAILED = 'MARK_LOCAL_TODO_AS_DONE_OR_EMPHASIZED_FAILED';
export type T_MARK_LOCAL_TODO_AS_DONE_OR_EMPHASIZED_FAILED = typeof MARK_LOCAL_TODO_AS_DONE_OR_EMPHASIZED_FAILED;

export const MARK_LOCAL_TODO_AS_DONE_WITH_DATE_SUCCESS = 'MARK_LOCAL_TODO_AS_DONE_WITH_DATE_SUCCESS';
export type T_MARK_LOCAL_TODO_AS_DONE_WITH_DATE_SUCCESS = typeof MARK_LOCAL_TODO_AS_DONE_WITH_DATE_SUCCESS;

export const MARK_LOCAL_TODO_AS_DONE_WITH_DATE_FAILED = 'MARK_LOCAL_TODO_AS_DONE_WITH_DATE_FAILED';
export type T_MARK_LOCAL_TODO_AS_DONE_WITH_DATE_FAILED = typeof MARK_LOCAL_TODO_AS_DONE_WITH_DATE_FAILED;

export const DELETE_LOCAL_TODO_SUCCESS = 'DELETE_LOCAL_TODO_SUCCESS';
export type T_DELETE_LOCAL_TODO_SUCCESS = typeof DELETE_LOCAL_TODO_SUCCESS;

export const DELETE_LOCAL_TODO_FAILED = 'DELETE_LOCAL_TODO_FAILED';
export type T_DELETE_LOCAL_TODO_FAILED = typeof DELETE_LOCAL_TODO_FAILED;
