export const GET_USER_ACCOUNT = 'GET_USER_ACCOUNT';
export type T_GET_USER_ACCOUNT = typeof GET_USER_ACCOUNT;

export const GET_USER_ACCOUNT_FAILED = 'GET_USER_ACCOUNT_FAILED';
export type T_GET_USER_ACCOUNT_FAILED = typeof GET_USER_ACCOUNT_FAILED;

export const GET_USER_ACCOUNT_SUCCESS = 'GET_USER_ACCOUNT_SUCCESS';
export type T_GET_USER_ACCOUNT_SUCCESS = typeof GET_USER_ACCOUNT_SUCCESS;
